a = 5

try:
    c = a + b
    
except NameError:
    print("Erro!")

else:
    print(c)